name: Publish package on NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 22.12.0
          registry-url: https://registry.npmjs.org/
      - uses: jetli/wasm-pack-action@v0.4.0
      - run: yarn build:modules
      - run: yarn
      - run: yarn publish:modules
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn build:library
      - run: npm publish
        working-directory: ./packages/clawdio
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
